language: ruby
before_install:
  - gem install asciidoctor
branches:
  only:
    - master
script: asciidoctor wardley-maps-book.adoc -o index.html
deploy:
  provider: releases
  api_key: $API_KEY
  file: index.html
  skip_cleanup: true
  draft: true
