language: ruby
before_install:
  - gem install asciidoctor
branches:
  only:
    - master
script: asciidoctor wardley-maps-book.adoc -o docs/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $API_KEY
  keep_history: true
  local_dir: docs
  on:
    branch: master
